# docker/Dockerfile.tf-code -- tf-code variant
#
# Adds the TensorFlow GPU stack on top of the shared base-gpu image. See
# docker/Dockerfile.base-gpu and
# docs/superpowers/plans/2026-08-03-consolidate-images.md.
ARG BASE_IMAGE=ghcr.io/mul-cps/cps-jupyter-notebook-base-gpu:latest
FROM ${BASE_IMAGE}

USER root

# TensorFlow GPU stack (no addons)
RUN --mount=type=cache,target=/home/${NB_USER}/.cache/pip \
    pip install --upgrade \
    "tensorflow[and-cuda]==2.21.*" \
    tensorflow-datasets \
    keras \
    tf-keras \
    scikit-learn \
    pandas \
    seaborn \
    matplotlib

USER root
WORKDIR /home/${NB_USER}/work
